query getAnime($id: Int) {
  Media (id: $id, type: ANIME) {
    id
    title {
      romaji
      english
      native
    }
    coverImage {
      extraLarge
      large
      color
    }
    bannerImage
    season
    seasonYear
    format
    episodes
    averageScore
    popularity
		description
    
    status
		startDate {
		  year
		  month
		  day
		}
    endDate {
      year
      month
      day
    }
    studios {
      edges {
        node {
          name
        }
      }
    }
    source
    genres
    duration

    characters (sort: ROLE) {
      edges {
        node {
          name {
            full
          }
          image {
            medium
          }
      	}
        role
        voiceActors {
          name {
            full
          }
          languageV2
          image {
            medium
          }
        }
      }
    }
  }
}